class ContextForgeError(Exception): ...


class ConfigurationError(ContextForgeError): ...


class SessionConfigError(ContextForgeError): ...


class AuthenticationError(ContextForgeError): ...


class ItemNotFoundError(ContextForgeError): ...


class ProviderServerError(ContextForgeError): ...


class CacheError(ContextForgeError): ...


class LLMError(ContextForgeError): ...


class ValidationError(ContextForgeError): ...


class ProviderNotRegisteredError(ContextForgeError): ...


class LLMEngineNotRegisteredError(ContextForgeError): ...


class ResourceResolverNotRegisteredError(ContextForgeError): ...
